use_frameworks!

platform :ios, '13.0'

target 'CoreData_Example' do
  pod 'SMCoreData', :path => '../'

  target 'CoreData_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
